DefaultContentLanguage = "ko"
baseURL = "https://aesopos.co.kr"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "aesoposinc"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.ko]
contentDir = "content/korea"
home = "홈"
languageCode = "ko-kr"
languageName = "Ko"
weight = 1
[[menu.main]]
URL = "portfolio"
name = "포트폴리오"
weight = 3
[[menu.main]]
URL = "services"
name = "서비스"
weight = 2
[[menu.main]]
URL = "team"
name = "팀원소개"
weight = 4
[[menu.main]]
URL = "blog"
name = "이야기"
weight = 5
[[menu.main]]
URL = "contact"
name = "고객지원"
weight = 6
[[menu.main]]
URL = "about"
name = "회사소개"
weight = 1
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analitycs_id = "UA-156657834-1"
logo = "images/favicon.png"
post_share = true
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyATccESqUYbZ4N7eCEaHjqifzQmwqF6nuU&libraries=places"
map_latitude = "36.322181"
map_longitude = "127.410475"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/aesoposinc/"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/EEbrISEmaq0eyP6"
[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UCsQXmhPu_t332OTCVSQHYFg"
[[params.social]]
icon = "ti-instagram"
link = "#"
